{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:14: AssertionError"}, "description": "this test fails", "start": 1611749448888, "stop": 1611749448889, "uuid": "fbe2bc3a-b7be-4d6c-88b4-fc94b98668aa", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "17252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}